---
- name: Copy httpd phpPgAdmin.conf
  copy:
    src: phpPgAdmin.conf
    dest: /etc/httpd/conf.d/phpPgAdmin.conf
    backup: yes
  notify: Restart httpd

- name: Copy config.inc.php
  copy:
    src: config.inc.php
    dest: /usr/share/phpPgAdmin/conf/config.inc.php
    backup: yes
