---
- name: Install Grails
  command: bash -lc "sdk install grails {{ grails_version }}"

- name: Allow Tomcat
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes
