---
- name: Checkout Redmine codes
  subversion:
    repo: "{{ redmine_svn_url }}"
    dest: "{{ redmine_dir }}"

- name: Create database.yml
  template:
    src: database.yml.j2
    dest: "{{ redmine_dir }}/config/database.yml"
    force: no

- name: Create configuration.yml
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_dir }}/config/configuration.yml"
    force: no

- name: Config gem packages
  command: /usr/local/rbenv/shims/bundle config build.pg --with-pg-config=/usr/pgsql-9.6/bin/pg_config
  args:
    chdir: "{{ redmine_dir }}"

- name: Install gem packages
  bundler:
    state: present
    chdir: "{{ redmine_dir }}"
    gem_path: vendor/bundle
    exclude_groups: development test
    executable: /usr/local/rbenv/shims/bundle

- name: Update gem packages
  bundler:
    state: latest
    chdir: "{{ redmine_dir }}"
    executable: /usr/local/rbenv/shims/bundle
