---
- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes

- name: Template redmine.conf
  become: yes
  template:
    src: redmine.conf.j2
    dest: /etc/httpd/conf.d/redmine.conf
  notify: Restart httpd

- name: Change Redmine directory owner
  file:
    path: "{{ redmine_dir }}"
    owner: apache
    group: apache
    recurse: yes
  notify: Restart httpd

- name: Apply patch to redmine.conf
  patch:
    src: redmine.conf.patch
    dest: /etc/httpd/conf.d/redmine.conf
  notify: Restart httpd
