---
- name: Install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: Add Docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Disable Docker repository
  command: yum-config-manager --disable docker-ce-stable

- name: Make cache
  command: yum makecache fast
