---
- name: Apply patch to phpPgAdmin.conf
  patch:
    src: phpPgAdmin.conf.patch
    dest: /etc/httpd/conf.d/phpPgAdmin.conf
  notify: Restart httpd

- name: Apply patch to config.inc.php
  patch:
    src: config.inc.php.patch
    dest: /etc/phpPgAdmin/config.inc.php
